# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A Duration represents a signed, fixed-length span of time represented
# as a count of seconds and fractions of seconds at nanosecond
# resolution. It is independent of any calendar and concepts like "day"
# or "month". It is related to Timestamp in that the difference between
# two Timestamp values is a Duration and it can be added or subtracted
# from a Timestamp. Range is approximately +-10,000 years.
#
# Based on google protobuf duration definition: <https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/duration.proto>
class Duration(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Duration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Signed seconds of the span of time. Must be from -315,576,000,000
    # to +315,576,000,000 inclusive. Note: these bounds are computed from:
    # 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
    # Duration
    def Seconds(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Signed fractions of a second at nanosecond resolution of the span
    # of time. Durations less than one second are represented with a 0
    # `seconds` field and a positive or negative `nanos` field. For durations
    # of one second or more, a non-zero value for the `nanos` field must be
    # of the same sign as the `seconds` field. Must be from -999,999,999
    # to +999,999,999 inclusive.
    # Duration
    def Nanos(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateDuration(builder, seconds, nanos):
    builder.Prep(8, 16)
    builder.Pad(4)
    builder.PrependInt32(nanos)
    builder.PrependInt64(seconds)
    return builder.Offset()


class DurationT(object):

    # DurationT
    def __init__(
        self,
        seconds = 0,
        nanos = 0,
    ):
        self.seconds = seconds  # type: int
        self.nanos = nanos  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        duration = Duration()
        duration.Init(buf, pos)
        return cls.InitFromObj(duration)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, duration):
        x = DurationT()
        x._UnPack(duration)
        return x

    # DurationT
    def _UnPack(self, duration):
        if duration is None:
            return
        self.seconds = duration.Seconds()
        self.nanos = duration.Nanos()

    # DurationT
    def Pack(self, builder):
        return CreateDuration(builder, self.seconds, self.nanos)
