# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# An event that describes a list of providers that have just changed.
class ProvidersChangedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProvidersChangedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProvidersChangedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProvidersChangedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A list of providers that have just been changed.
    # ProvidersChangedEvent
    def Providers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.ProviderList import ProviderList
            obj = ProviderList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ProvidersChangedEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    ProvidersChangedEventStart(builder)

def ProvidersChangedEventAddProviders(builder, providers):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(providers), 0)

def AddProviders(builder, providers):
    ProvidersChangedEventAddProviders(builder, providers)

def ProvidersChangedEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProvidersChangedEventEnd(builder)

import weidmueller.ucontrol.hub.ProviderList
try:
    from typing import Optional
except:
    pass

class ProvidersChangedEventT(object):

    # ProvidersChangedEventT
    def __init__(
        self,
        providers = None,
    ):
        self.providers = providers  # type: Optional[weidmueller.ucontrol.hub.ProviderList.ProviderListT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        providersChangedEvent = ProvidersChangedEvent()
        providersChangedEvent.Init(buf, pos)
        return cls.InitFromObj(providersChangedEvent)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, providersChangedEvent):
        x = ProvidersChangedEventT()
        x._UnPack(providersChangedEvent)
        return x

    # ProvidersChangedEventT
    def _UnPack(self, providersChangedEvent):
        if providersChangedEvent is None:
            return
        if providersChangedEvent.Providers() is not None:
            self.providers = weidmueller.ucontrol.hub.ProviderList.ProviderListT.InitFromObj(providersChangedEvent.Providers())

    # ProvidersChangedEventT
    def Pack(self, builder):
        if self.providers is not None:
            providers = self.providers.Pack(builder)
        ProvidersChangedEventStart(builder)
        if self.providers is not None:
            ProvidersChangedEventAddProviders(builder, providers)
        providersChangedEvent = ProvidersChangedEventEnd(builder)
        return providersChangedEvent
