# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A list of providers that provide variables to consumers.
class ProviderList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProviderList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProviderList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProviderList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The list of providers.
    # ProviderList
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from weidmueller.ucontrol.hub.Provider import Provider
            obj = Provider()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProviderList
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProviderList
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ProviderListStart(builder):
    builder.StartObject(1)

def Start(builder):
    ProviderListStart(builder)

def ProviderListAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    ProviderListAddItems(builder, items)

def ProviderListStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return ProviderListStartItemsVector(builder, numElems)

def ProviderListEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProviderListEnd(builder)

import weidmueller.ucontrol.hub.Provider
try:
    from typing import List
except:
    pass

class ProviderListT(object):

    # ProviderListT
    def __init__(
        self,
        items = None,
    ):
        self.items = items  # type: Optional[List[weidmueller.ucontrol.hub.Provider.ProviderT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        providerList = ProviderList()
        providerList.Init(buf, pos)
        return cls.InitFromObj(providerList)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, providerList):
        x = ProviderListT()
        x._UnPack(providerList)
        return x

    # ProviderListT
    def _UnPack(self, providerList):
        if providerList is None:
            return
        if not providerList.ItemsIsNone():
            self.items = []
            for i in range(providerList.ItemsLength()):
                if providerList.Items(i) is None:
                    self.items.append(None)
                else:
                    provider_ = weidmueller.ucontrol.hub.Provider.ProviderT.InitFromObj(providerList.Items(i))
                    self.items.append(provider_)

    # ProviderListT
    def Pack(self, builder):
        if self.items is not None:
            itemslist = []
            for i in range(len(self.items)):
                itemslist.append(self.items[i].Pack(builder))
            ProviderListStartItemsVector(builder, len(self.items))
            for i in reversed(range(len(self.items))):
                builder.PrependUOffsetTRelative(itemslist[i])
            items = builder.EndVector()
        ProviderListStart(builder)
        if self.items is not None:
            ProviderListAddItems(builder, items)
        providerList = ProviderListEnd(builder)
        return providerList
