# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A definition of a provider's provided variables.
#
# Definition elements have a flat list instead of a hierarchy structure.
# They support the folder concept as a means of grouping definitions by using
# a shared key prefix for the grouped definitions.
# This means that the grouped definitions have keys that begin with a common
# string.
# This common string, or shared prefix, is the folder key.
#
# For security reasons, the provider id must be extracted from the
# communication channel.
class ProviderDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProviderDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProviderDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProviderDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The fingerprint is a version identification of the provider definition.
    #
    # Therefore, the fingerprint can be used by a consumer to check whether
    # the provider's definition matches the values received.
    # Whenever a provider definition changed, the provider must change the
    # fingerprint.
    # ProviderDefinition
    def Fingerprint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # The list of variable definitions.
    # ProviderDefinition
    def VariableDefinitions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from weidmueller.ucontrol.hub.VariableDefinition import VariableDefinition
            obj = VariableDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProviderDefinition
    def VariableDefinitionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProviderDefinition
    def VariableDefinitionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # The current state of the provider definition. The state will be set by the registry.
    # ProviderDefinition
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ProviderDefinitionStart(builder):
    builder.StartObject(3)

def Start(builder):
    ProviderDefinitionStart(builder)

def ProviderDefinitionAddFingerprint(builder, fingerprint):
    builder.PrependUint64Slot(0, fingerprint, 0)

def AddFingerprint(builder, fingerprint):
    ProviderDefinitionAddFingerprint(builder, fingerprint)

def ProviderDefinitionAddVariableDefinitions(builder, variableDefinitions):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(variableDefinitions), 0)

def AddVariableDefinitions(builder, variableDefinitions):
    ProviderDefinitionAddVariableDefinitions(builder, variableDefinitions)

def ProviderDefinitionStartVariableDefinitionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVariableDefinitionsVector(builder, numElems):
    return ProviderDefinitionStartVariableDefinitionsVector(builder, numElems)

def ProviderDefinitionAddState(builder, state):
    builder.PrependUint8Slot(2, state, 0)

def AddState(builder, state):
    ProviderDefinitionAddState(builder, state)

def ProviderDefinitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProviderDefinitionEnd(builder)

import weidmueller.ucontrol.hub.VariableDefinition
try:
    from typing import List
except:
    pass

class ProviderDefinitionT(object):

    # ProviderDefinitionT
    def __init__(
        self,
        fingerprint = 0,
        variableDefinitions = None,
        state = 0,
    ):
        self.fingerprint = fingerprint  # type: int
        self.variableDefinitions = variableDefinitions  # type: Optional[List[weidmueller.ucontrol.hub.VariableDefinition.VariableDefinitionT]]
        self.state = state  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        providerDefinition = ProviderDefinition()
        providerDefinition.Init(buf, pos)
        return cls.InitFromObj(providerDefinition)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, providerDefinition):
        x = ProviderDefinitionT()
        x._UnPack(providerDefinition)
        return x

    # ProviderDefinitionT
    def _UnPack(self, providerDefinition):
        if providerDefinition is None:
            return
        self.fingerprint = providerDefinition.Fingerprint()
        if not providerDefinition.VariableDefinitionsIsNone():
            self.variableDefinitions = []
            for i in range(providerDefinition.VariableDefinitionsLength()):
                if providerDefinition.VariableDefinitions(i) is None:
                    self.variableDefinitions.append(None)
                else:
                    variableDefinition_ = weidmueller.ucontrol.hub.VariableDefinition.VariableDefinitionT.InitFromObj(providerDefinition.VariableDefinitions(i))
                    self.variableDefinitions.append(variableDefinition_)
        self.state = providerDefinition.State()

    # ProviderDefinitionT
    def Pack(self, builder):
        if self.variableDefinitions is not None:
            variableDefinitionslist = []
            for i in range(len(self.variableDefinitions)):
                variableDefinitionslist.append(self.variableDefinitions[i].Pack(builder))
            ProviderDefinitionStartVariableDefinitionsVector(builder, len(self.variableDefinitions))
            for i in reversed(range(len(self.variableDefinitions))):
                builder.PrependUOffsetTRelative(variableDefinitionslist[i])
            variableDefinitions = builder.EndVector()
        ProviderDefinitionStart(builder)
        ProviderDefinitionAddFingerprint(builder, self.fingerprint)
        if self.variableDefinitions is not None:
            ProviderDefinitionAddVariableDefinitions(builder, variableDefinitions)
        ProviderDefinitionAddState(builder, self.state)
        providerDefinition = ProviderDefinitionEnd(builder)
        return providerDefinition
