# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A provider that provides variables to consumers.
class Provider(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Provider()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProvider(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Provider
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The id of the provider.
    # Provider
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ProviderStart(builder):
    builder.StartObject(1)

def Start(builder):
    ProviderStart(builder)

def ProviderAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ProviderAddId(builder, id)

def ProviderEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProviderEnd(builder)


class ProviderT(object):

    # ProviderT
    def __init__(
        self,
        id = None,
    ):
        self.id = id  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        provider = Provider()
        provider.Init(buf, pos)
        return cls.InitFromObj(provider)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, provider):
        x = ProviderT()
        x._UnPack(provider)
        return x

    # ProviderT
    def _UnPack(self, provider):
        if provider is None:
            return
        self.id = provider.Id()

    # ProviderT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        ProviderStart(builder)
        if self.id is not None:
            ProviderAddId(builder, id)
        provider = ProviderEnd(builder)
        return provider
