# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# An event that describes a provider's definition that has just changed.
class ProviderDefinitionChangedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProviderDefinitionChangedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProviderDefinitionChangedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProviderDefinitionChangedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A definition that has just been changed.
    # If the provider_definition is null, the provider is removed.
    # ProviderDefinitionChangedEvent
    def ProviderDefinition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.ProviderDefinition import ProviderDefinition
            obj = ProviderDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ProviderDefinitionChangedEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    ProviderDefinitionChangedEventStart(builder)

def ProviderDefinitionChangedEventAddProviderDefinition(builder, providerDefinition):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(providerDefinition), 0)

def AddProviderDefinition(builder, providerDefinition):
    ProviderDefinitionChangedEventAddProviderDefinition(builder, providerDefinition)

def ProviderDefinitionChangedEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProviderDefinitionChangedEventEnd(builder)

import weidmueller.ucontrol.hub.ProviderDefinition
try:
    from typing import Optional
except:
    pass

class ProviderDefinitionChangedEventT(object):

    # ProviderDefinitionChangedEventT
    def __init__(
        self,
        providerDefinition = None,
    ):
        self.providerDefinition = providerDefinition  # type: Optional[weidmueller.ucontrol.hub.ProviderDefinition.ProviderDefinitionT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        providerDefinitionChangedEvent = ProviderDefinitionChangedEvent()
        providerDefinitionChangedEvent.Init(buf, pos)
        return cls.InitFromObj(providerDefinitionChangedEvent)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, providerDefinitionChangedEvent):
        x = ProviderDefinitionChangedEventT()
        x._UnPack(providerDefinitionChangedEvent)
        return x

    # ProviderDefinitionChangedEventT
    def _UnPack(self, providerDefinitionChangedEvent):
        if providerDefinitionChangedEvent is None:
            return
        if providerDefinitionChangedEvent.ProviderDefinition() is not None:
            self.providerDefinition = weidmueller.ucontrol.hub.ProviderDefinition.ProviderDefinitionT.InitFromObj(providerDefinitionChangedEvent.ProviderDefinition())

    # ProviderDefinitionChangedEventT
    def Pack(self, builder):
        if self.providerDefinition is not None:
            providerDefinition = self.providerDefinition.Pack(builder)
        ProviderDefinitionChangedEventStart(builder)
        if self.providerDefinition is not None:
            ProviderDefinitionChangedEventAddProviderDefinition(builder, providerDefinition)
        providerDefinitionChangedEvent = ProviderDefinitionChangedEventEnd(builder)
        return providerDefinitionChangedEvent
