# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A query response that returns a requested list of providers.
class ReadProvidersQueryResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadProvidersQueryResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadProvidersQueryResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadProvidersQueryResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A list of providers that have been requested.
    # ReadProvidersQueryResponse
    def Providers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.ProviderList import ProviderList
            obj = ProviderList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ReadProvidersQueryResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReadProvidersQueryResponseStart(builder)

def ReadProvidersQueryResponseAddProviders(builder, providers):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(providers), 0)

def AddProviders(builder, providers):
    ReadProvidersQueryResponseAddProviders(builder, providers)

def ReadProvidersQueryResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadProvidersQueryResponseEnd(builder)

import weidmueller.ucontrol.hub.ProviderList
try:
    from typing import Optional
except:
    pass

class ReadProvidersQueryResponseT(object):

    # ReadProvidersQueryResponseT
    def __init__(
        self,
        providers = None,
    ):
        self.providers = providers  # type: Optional[weidmueller.ucontrol.hub.ProviderList.ProviderListT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        readProvidersQueryResponse = ReadProvidersQueryResponse()
        readProvidersQueryResponse.Init(buf, pos)
        return cls.InitFromObj(readProvidersQueryResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, readProvidersQueryResponse):
        x = ReadProvidersQueryResponseT()
        x._UnPack(readProvidersQueryResponse)
        return x

    # ReadProvidersQueryResponseT
    def _UnPack(self, readProvidersQueryResponse):
        if readProvidersQueryResponse is None:
            return
        if readProvidersQueryResponse.Providers() is not None:
            self.providers = weidmueller.ucontrol.hub.ProviderList.ProviderListT.InitFromObj(readProvidersQueryResponse.Providers())

    # ReadProvidersQueryResponseT
    def Pack(self, builder):
        if self.providers is not None:
            providers = self.providers.Pack(builder)
        ReadProvidersQueryResponseStart(builder)
        if self.providers is not None:
            ReadProvidersQueryResponseAddProviders(builder, providers)
        readProvidersQueryResponse = ReadProvidersQueryResponseEnd(builder)
        return readProvidersQueryResponse
