# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A query request that requests a list of providers.
class ReadProvidersQueryRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadProvidersQueryRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadProvidersQueryRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadProvidersQueryRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ReadProvidersQueryRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    ReadProvidersQueryRequestStart(builder)

def ReadProvidersQueryRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadProvidersQueryRequestEnd(builder)


class ReadProvidersQueryRequestT(object):

    # ReadProvidersQueryRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        readProvidersQueryRequest = ReadProvidersQueryRequest()
        readProvidersQueryRequest.Init(buf, pos)
        return cls.InitFromObj(readProvidersQueryRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, readProvidersQueryRequest):
        x = ReadProvidersQueryRequestT()
        x._UnPack(readProvidersQueryRequest)
        return x

    # ReadProvidersQueryRequestT
    def _UnPack(self, readProvidersQueryRequest):
        if readProvidersQueryRequest is None:
            return

    # ReadProvidersQueryRequestT
    def Pack(self, builder):
        ReadProvidersQueryRequestStart(builder)
        readProvidersQueryRequest = ReadProvidersQueryRequestEnd(builder)
        return readProvidersQueryRequest
