# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A query Response that returns a requested provider's definition.
class ReadProviderDefinitionQueryResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadProviderDefinitionQueryResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadProviderDefinitionQueryResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadProviderDefinitionQueryResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A provider's definition that has been requested.
    # ReadProviderDefinitionQueryResponse
    def ProviderDefinition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.ProviderDefinition import ProviderDefinition
            obj = ProviderDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ReadProviderDefinitionQueryResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReadProviderDefinitionQueryResponseStart(builder)

def ReadProviderDefinitionQueryResponseAddProviderDefinition(builder, providerDefinition):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(providerDefinition), 0)

def AddProviderDefinition(builder, providerDefinition):
    ReadProviderDefinitionQueryResponseAddProviderDefinition(builder, providerDefinition)

def ReadProviderDefinitionQueryResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadProviderDefinitionQueryResponseEnd(builder)

import weidmueller.ucontrol.hub.ProviderDefinition
try:
    from typing import Optional
except:
    pass

class ReadProviderDefinitionQueryResponseT(object):

    # ReadProviderDefinitionQueryResponseT
    def __init__(
        self,
        providerDefinition = None,
    ):
        self.providerDefinition = providerDefinition  # type: Optional[weidmueller.ucontrol.hub.ProviderDefinition.ProviderDefinitionT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        readProviderDefinitionQueryResponse = ReadProviderDefinitionQueryResponse()
        readProviderDefinitionQueryResponse.Init(buf, pos)
        return cls.InitFromObj(readProviderDefinitionQueryResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, readProviderDefinitionQueryResponse):
        x = ReadProviderDefinitionQueryResponseT()
        x._UnPack(readProviderDefinitionQueryResponse)
        return x

    # ReadProviderDefinitionQueryResponseT
    def _UnPack(self, readProviderDefinitionQueryResponse):
        if readProviderDefinitionQueryResponse is None:
            return
        if readProviderDefinitionQueryResponse.ProviderDefinition() is not None:
            self.providerDefinition = weidmueller.ucontrol.hub.ProviderDefinition.ProviderDefinitionT.InitFromObj(readProviderDefinitionQueryResponse.ProviderDefinition())

    # ReadProviderDefinitionQueryResponseT
    def Pack(self, builder):
        if self.providerDefinition is not None:
            providerDefinition = self.providerDefinition.Pack(builder)
        ReadProviderDefinitionQueryResponseStart(builder)
        if self.providerDefinition is not None:
            ReadProviderDefinitionQueryResponseAddProviderDefinition(builder, providerDefinition)
        readProviderDefinitionQueryResponse = ReadProviderDefinitionQueryResponseEnd(builder)
        return readProviderDefinitionQueryResponse
