# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A query request that requests a provider's definition.
class ReadProviderDefinitionQueryRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadProviderDefinitionQueryRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadProviderDefinitionQueryRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadProviderDefinitionQueryRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ReadProviderDefinitionQueryRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    ReadProviderDefinitionQueryRequestStart(builder)

def ReadProviderDefinitionQueryRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadProviderDefinitionQueryRequestEnd(builder)


class ReadProviderDefinitionQueryRequestT(object):

    # ReadProviderDefinitionQueryRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        readProviderDefinitionQueryRequest = ReadProviderDefinitionQueryRequest()
        readProviderDefinitionQueryRequest.Init(buf, pos)
        return cls.InitFromObj(readProviderDefinitionQueryRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, readProviderDefinitionQueryRequest):
        x = ReadProviderDefinitionQueryRequestT()
        x._UnPack(readProviderDefinitionQueryRequest)
        return x

    # ReadProviderDefinitionQueryRequestT
    def _UnPack(self, readProviderDefinitionQueryRequest):
        if readProviderDefinitionQueryRequest is None:
            return

    # ReadProviderDefinitionQueryRequestT
    def Pack(self, builder):
        ReadProviderDefinitionQueryRequestStart(builder)
        readProviderDefinitionQueryRequest = ReadProviderDefinitionQueryRequestEnd(builder)
        return readProviderDefinitionQueryRequest
