# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A query response that responds to a requested list of provider variables.
class ReadVariablesQueryResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadVariablesQueryResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadVariablesQueryResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadVariablesQueryResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A list of variables that have been requested.
    # ReadVariablesQueryResponse
    def Variables(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.VariableList import VariableList
            obj = VariableList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ReadVariablesQueryResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReadVariablesQueryResponseStart(builder)

def ReadVariablesQueryResponseAddVariables(builder, variables):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(variables), 0)

def AddVariables(builder, variables):
    ReadVariablesQueryResponseAddVariables(builder, variables)

def ReadVariablesQueryResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadVariablesQueryResponseEnd(builder)

import weidmueller.ucontrol.hub.VariableList
try:
    from typing import Optional
except:
    pass

class ReadVariablesQueryResponseT(object):

    # ReadVariablesQueryResponseT
    def __init__(
        self,
        variables = None,
    ):
        self.variables = variables  # type: Optional[weidmueller.ucontrol.hub.VariableList.VariableListT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        readVariablesQueryResponse = ReadVariablesQueryResponse()
        readVariablesQueryResponse.Init(buf, pos)
        return cls.InitFromObj(readVariablesQueryResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, readVariablesQueryResponse):
        x = ReadVariablesQueryResponseT()
        x._UnPack(readVariablesQueryResponse)
        return x

    # ReadVariablesQueryResponseT
    def _UnPack(self, readVariablesQueryResponse):
        if readVariablesQueryResponse is None:
            return
        if readVariablesQueryResponse.Variables() is not None:
            self.variables = weidmueller.ucontrol.hub.VariableList.VariableListT.InitFromObj(readVariablesQueryResponse.Variables())

    # ReadVariablesQueryResponseT
    def Pack(self, builder):
        if self.variables is not None:
            variables = self.variables.Pack(builder)
        ReadVariablesQueryResponseStart(builder)
        if self.variables is not None:
            ReadVariablesQueryResponseAddVariables(builder, variables)
        readVariablesQueryResponse = ReadVariablesQueryResponseEnd(builder)
        return readVariablesQueryResponse
