# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A query that requests a list of variables from a single provider.
#
# The returned variables can be filtered using an array of IDs.
class ReadVariablesQueryRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadVariablesQueryRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadVariablesQueryRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadVariablesQueryRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # An array of IDs which serves as a filter: Only those variables with the given IDs shall be returned by the provider.
    # When no IDs are given, we expect the provider to return all of its variables in the response.
    # ReadVariablesQueryRequest
    def Ids(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ReadVariablesQueryRequest
    def IdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # ReadVariablesQueryRequest
    def IdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReadVariablesQueryRequest
    def IdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ReadVariablesQueryRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReadVariablesQueryRequestStart(builder)

def ReadVariablesQueryRequestAddIds(builder, ids):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ids), 0)

def AddIds(builder, ids):
    ReadVariablesQueryRequestAddIds(builder, ids)

def ReadVariablesQueryRequestStartIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIdsVector(builder, numElems):
    return ReadVariablesQueryRequestStartIdsVector(builder, numElems)

def ReadVariablesQueryRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadVariablesQueryRequestEnd(builder)

try:
    from typing import List
except:
    pass

class ReadVariablesQueryRequestT(object):

    # ReadVariablesQueryRequestT
    def __init__(
        self,
        ids = None,
    ):
        self.ids = ids  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        readVariablesQueryRequest = ReadVariablesQueryRequest()
        readVariablesQueryRequest.Init(buf, pos)
        return cls.InitFromObj(readVariablesQueryRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, readVariablesQueryRequest):
        x = ReadVariablesQueryRequestT()
        x._UnPack(readVariablesQueryRequest)
        return x

    # ReadVariablesQueryRequestT
    def _UnPack(self, readVariablesQueryRequest):
        if readVariablesQueryRequest is None:
            return
        if not readVariablesQueryRequest.IdsIsNone():
            if np is None:
                self.ids = []
                for i in range(readVariablesQueryRequest.IdsLength()):
                    self.ids.append(readVariablesQueryRequest.Ids(i))
            else:
                self.ids = readVariablesQueryRequest.IdsAsNumpy()

    # ReadVariablesQueryRequestT
    def Pack(self, builder):
        if self.ids is not None:
            if np is not None and type(self.ids) is np.ndarray:
                ids = builder.CreateNumpyVector(self.ids)
            else:
                ReadVariablesQueryRequestStartIdsVector(builder, len(self.ids))
                for i in reversed(range(len(self.ids))):
                    builder.PrependUint32(self.ids[i])
                ids = builder.EndVector()
        ReadVariablesQueryRequestStart(builder)
        if self.ids is not None:
            ReadVariablesQueryRequestAddIds(builder, ids)
        readVariablesQueryRequest = ReadVariablesQueryRequestEnd(builder)
        return readVariablesQueryRequest
