# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# An event that describes a state that has just changed.
class StateChangedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StateChangedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStateChangedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StateChangedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A state that has just been changed.
    # StateChangedEvent
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def StateChangedEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    StateChangedEventStart(builder)

def StateChangedEventAddState(builder, state):
    builder.PrependInt8Slot(0, state, 0)

def AddState(builder, state):
    StateChangedEventAddState(builder, state)

def StateChangedEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return StateChangedEventEnd(builder)


class StateChangedEventT(object):

    # StateChangedEventT
    def __init__(
        self,
        state = 0,
    ):
        self.state = state  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stateChangedEvent = StateChangedEvent()
        stateChangedEvent.Init(buf, pos)
        return cls.InitFromObj(stateChangedEvent)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stateChangedEvent):
        x = StateChangedEventT()
        x._UnPack(stateChangedEvent)
        return x

    # StateChangedEventT
    def _UnPack(self, stateChangedEvent):
        if stateChangedEvent is None:
            return
        self.state = stateChangedEvent.State()

    # StateChangedEventT
    def Pack(self, builder):
        StateChangedEventStart(builder)
        StateChangedEventAddState(builder, self.state)
        stateChangedEvent = StateChangedEventEnd(builder)
        return stateChangedEvent
