# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

# A state of a service.
#
# The state names are based on
# [the status names of the systemd services](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#is-system-running).
class State(object):
    UNSPECIFIED = 0
    RUNNING = 1
    STOPPING = 2
