# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A timestamp measured by the number of nanoseconds that have elapsed
# since 00:00:00 UTC on 1 January 1970, which is referred to as the Unix
# epoch, without adjustments made due to leap seconds.
#
# Based on google protobuf timestamp definition: <https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto>
class Timestamp(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Timestamp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Represents seconds of UTC time since Unix epoch
    # 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
    # 9999-12-31T23:59:59Z inclusive.
    # Timestamp
    def Seconds(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Non-negative fractions of a second at nanosecond resolution. Negative
    # second values with fractions must still have non-negative nanos values
    # that count forward in time. Must be from 0 to 999,999,999
    # inclusive.
    # Timestamp
    def Nanos(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateTimestamp(builder, seconds, nanos):
    builder.Prep(8, 16)
    builder.Pad(4)
    builder.PrependInt32(nanos)
    builder.PrependInt64(seconds)
    return builder.Offset()


class TimestampT(object):

    # TimestampT
    def __init__(
        self,
        seconds = 0,
        nanos = 0,
    ):
        self.seconds = seconds  # type: int
        self.nanos = nanos  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        timestamp = Timestamp()
        timestamp.Init(buf, pos)
        return cls.InitFromObj(timestamp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, timestamp):
        x = TimestampT()
        x._UnPack(timestamp)
        return x

    # TimestampT
    def _UnPack(self, timestamp):
        if timestamp is None:
            return
        self.seconds = timestamp.Seconds()
        self.nanos = timestamp.Nanos()

    # TimestampT
    def Pack(self, builder):
        return CreateTimestamp(builder, self.seconds, self.nanos)
