# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Uuid(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Uuid
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Uuid
    def Upper(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Uuid
    def Lower(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateUuid(builder, upper, lower):
    builder.Prep(8, 16)
    builder.PrependUint64(lower)
    builder.PrependUint64(upper)
    return builder.Offset()


class UuidT(object):

    # UuidT
    def __init__(
        self,
        upper = 0,
        lower = 0,
    ):
        self.upper = upper  # type: int
        self.lower = lower  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uuid = Uuid()
        uuid.Init(buf, pos)
        return cls.InitFromObj(uuid)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uuid):
        x = UuidT()
        x._UnPack(uuid)
        return x

    # UuidT
    def _UnPack(self, uuid):
        if uuid is None:
            return
        self.upper = uuid.Upper()
        self.lower = uuid.Lower()

    # UuidT
    def Pack(self, builder):
        return CreateUuid(builder, self.upper, self.lower)
