# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

# The data type of a variable.
class VariableDataType(object):
    UNSPECIFIED = 0
    BOOLEAN = 1
    DURATION = 2
    FLOAT64 = 3
    INT64 = 4
    STRING = 5
    TIMESTAMP = 6
