# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

# The value of a variable.
class VariableValue(object):
    NONE = 0
    Boolean = 1
    Duration = 2
    Float64 = 3
    Int64 = 4
    String = 5
    Timestamp = 6

def VariableValueCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == VariableValue.Boolean:
        import weidmueller.ucontrol.hub.VariableValueBoolean
        return weidmueller.ucontrol.hub.VariableValueBoolean.VariableValueBooleanT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VariableValue.Duration:
        import weidmueller.ucontrol.hub.VariableValueDuration
        return weidmueller.ucontrol.hub.VariableValueDuration.VariableValueDurationT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VariableValue.Float64:
        import weidmueller.ucontrol.hub.VariableValueFloat64
        return weidmueller.ucontrol.hub.VariableValueFloat64.VariableValueFloat64T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VariableValue.Int64:
        import weidmueller.ucontrol.hub.VariableValueInt64
        return weidmueller.ucontrol.hub.VariableValueInt64.VariableValueInt64T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VariableValue.String:
        import weidmueller.ucontrol.hub.VariableValueString
        return weidmueller.ucontrol.hub.VariableValueString.VariableValueStringT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == VariableValue.Timestamp:
        import weidmueller.ucontrol.hub.VariableValueTimestamp
        return weidmueller.ucontrol.hub.VariableValueTimestamp.VariableValueTimestampT.InitFromBuf(table.Bytes, table.Pos)
    return None
