# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

# The quality of a variable.
#
# This is set by the provider and indicates the quality of a variable value.
# Check the documentation of the individual values for more information.
class VariableQuality(object):
    # Indicates that the value is not usable
    BAD = 0
    # Variable quality is uncertain without any specific reason, but may still be usable e.g. for display or other non critical purposes
    UNCERTAIN = 64
    # The variable has stopped updating and contains its last usable value
    UNCERTAIN_LAST_USABLE_VALUE = 67
    # Variable has not been written yet and still contains a default initial value
    UNCERTAIN_INITIAL_VALUE = 68
    # Indicates that the value is good and can be used without restrictions
    GOOD = 192
