# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A date and time value of a variable.
class VariableValueTimestamp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableValueTimestamp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableValueTimestamp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableValueTimestamp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariableValueTimestamp
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from weidmueller.ucontrol.hub.Timestamp import Timestamp
            obj = Timestamp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VariableValueTimestampStart(builder):
    builder.StartObject(1)

def Start(builder):
    VariableValueTimestampStart(builder)

def VariableValueTimestampAddValue(builder, value):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    VariableValueTimestampAddValue(builder, value)

def VariableValueTimestampEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableValueTimestampEnd(builder)

import weidmueller.ucontrol.hub.Timestamp
try:
    from typing import Optional
except:
    pass

class VariableValueTimestampT(object):

    # VariableValueTimestampT
    def __init__(
        self,
        value = None,
    ):
        self.value = value  # type: Optional[weidmueller.ucontrol.hub.Timestamp.TimestampT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableValueTimestamp = VariableValueTimestamp()
        variableValueTimestamp.Init(buf, pos)
        return cls.InitFromObj(variableValueTimestamp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableValueTimestamp):
        x = VariableValueTimestampT()
        x._UnPack(variableValueTimestamp)
        return x

    # VariableValueTimestampT
    def _UnPack(self, variableValueTimestamp):
        if variableValueTimestamp is None:
            return
        if variableValueTimestamp.Value() is not None:
            self.value = weidmueller.ucontrol.hub.Timestamp.TimestampT.InitFromObj(variableValueTimestamp.Value())

    # VariableValueTimestampT
    def Pack(self, builder):
        VariableValueTimestampStart(builder)
        if self.value is not None:
            value = self.value.Pack(builder)
            VariableValueTimestampAddValue(builder, value)
        variableValueTimestamp = VariableValueTimestampEnd(builder)
        return variableValueTimestamp
