# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A list of a provider's variables that match the provider's definition.
class VariableList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The fingerprint of the associated provider's definition.
    # VariableList
    def ProviderDefinitionFingerprint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # The timestamp for all changed variables. The base timestamp is the
    # fallback if no explicit was specified for the variable.
    #
    # Only set by the provider!
    # Consumers can set it to 0s and 0ns. This value is ignored by the
    # provider in a write command.
    # VariableList
    def BaseTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from weidmueller.ucontrol.hub.Timestamp import Timestamp
            obj = Timestamp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The items of the provider's variable list.
    # VariableList
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from weidmueller.ucontrol.hub.Variable import Variable
            obj = Variable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VariableList
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VariableList
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def VariableListStart(builder):
    builder.StartObject(3)

def Start(builder):
    VariableListStart(builder)

def VariableListAddProviderDefinitionFingerprint(builder, providerDefinitionFingerprint):
    builder.PrependUint64Slot(0, providerDefinitionFingerprint, 0)

def AddProviderDefinitionFingerprint(builder, providerDefinitionFingerprint):
    VariableListAddProviderDefinitionFingerprint(builder, providerDefinitionFingerprint)

def VariableListAddBaseTimestamp(builder, baseTimestamp):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(baseTimestamp), 0)

def AddBaseTimestamp(builder, baseTimestamp):
    VariableListAddBaseTimestamp(builder, baseTimestamp)

def VariableListAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    VariableListAddItems(builder, items)

def VariableListStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return VariableListStartItemsVector(builder, numElems)

def VariableListEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableListEnd(builder)

import weidmueller.ucontrol.hub.Timestamp
import weidmueller.ucontrol.hub.Variable
try:
    from typing import List, Optional
except:
    pass

class VariableListT(object):

    # VariableListT
    def __init__(
        self,
        providerDefinitionFingerprint = 0,
        baseTimestamp = None,
        items = None,
    ):
        self.providerDefinitionFingerprint = providerDefinitionFingerprint  # type: int
        self.baseTimestamp = baseTimestamp  # type: Optional[weidmueller.ucontrol.hub.Timestamp.TimestampT]
        self.items = items  # type: Optional[List[weidmueller.ucontrol.hub.Variable.VariableT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableList = VariableList()
        variableList.Init(buf, pos)
        return cls.InitFromObj(variableList)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableList):
        x = VariableListT()
        x._UnPack(variableList)
        return x

    # VariableListT
    def _UnPack(self, variableList):
        if variableList is None:
            return
        self.providerDefinitionFingerprint = variableList.ProviderDefinitionFingerprint()
        if variableList.BaseTimestamp() is not None:
            self.baseTimestamp = weidmueller.ucontrol.hub.Timestamp.TimestampT.InitFromObj(variableList.BaseTimestamp())
        if not variableList.ItemsIsNone():
            self.items = []
            for i in range(variableList.ItemsLength()):
                if variableList.Items(i) is None:
                    self.items.append(None)
                else:
                    variable_ = weidmueller.ucontrol.hub.Variable.VariableT.InitFromObj(variableList.Items(i))
                    self.items.append(variable_)

    # VariableListT
    def Pack(self, builder):
        if self.items is not None:
            itemslist = []
            for i in range(len(self.items)):
                itemslist.append(self.items[i].Pack(builder))
            VariableListStartItemsVector(builder, len(self.items))
            for i in reversed(range(len(self.items))):
                builder.PrependUOffsetTRelative(itemslist[i])
            items = builder.EndVector()
        VariableListStart(builder)
        VariableListAddProviderDefinitionFingerprint(builder, self.providerDefinitionFingerprint)
        if self.baseTimestamp is not None:
            baseTimestamp = self.baseTimestamp.Pack(builder)
            VariableListAddBaseTimestamp(builder, baseTimestamp)
        if self.items is not None:
            VariableListAddItems(builder, items)
        variableList = VariableListEnd(builder)
        return variableList
