# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A variable associated with the provider's definition.
class Variable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Variable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Variable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Variable
    def ValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # The value of the variable.
    # Variable
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # The ID of the variable associated with the provider's definition.
    # Variable
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The individual timestamp of the variable.
    #
    # Only set by the provider!
    # Consumers can left this empty. This value is ignored by the provider in
    # a write command.
    # Variable
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from weidmueller.ucontrol.hub.Timestamp import Timestamp
            obj = Timestamp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The quality of the variable.
    #
    # Only set by the provider!
    # Consumers can set it to BAD. This value is ignored by the provider
    # in a write command.
    # Variable
    def Quality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def VariableStart(builder):
    builder.StartObject(5)

def Start(builder):
    VariableStart(builder)

def VariableAddValueType(builder, valueType):
    builder.PrependUint8Slot(0, valueType, 0)

def AddValueType(builder, valueType):
    VariableAddValueType(builder, valueType)

def VariableAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    VariableAddValue(builder, value)

def VariableAddId(builder, id):
    builder.PrependUint32Slot(2, id, 0)

def AddId(builder, id):
    VariableAddId(builder, id)

def VariableAddTimestamp(builder, timestamp):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)

def AddTimestamp(builder, timestamp):
    VariableAddTimestamp(builder, timestamp)

def VariableAddQuality(builder, quality):
    builder.PrependUint8Slot(4, quality, 0)

def AddQuality(builder, quality):
    VariableAddQuality(builder, quality)

def VariableEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableEnd(builder)

import weidmueller.ucontrol.hub.Timestamp
import weidmueller.ucontrol.hub.VariableValue
import weidmueller.ucontrol.hub.VariableValueBoolean
import weidmueller.ucontrol.hub.VariableValueDuration
import weidmueller.ucontrol.hub.VariableValueFloat64
import weidmueller.ucontrol.hub.VariableValueInt64
import weidmueller.ucontrol.hub.VariableValueString
import weidmueller.ucontrol.hub.VariableValueTimestamp
try:
    from typing import Optional, Union
except:
    pass

class VariableT(object):

    # VariableT
    def __init__(
        self,
        valueType = 0,
        value = None,
        id = 0,
        timestamp = None,
        quality = 0,
    ):
        self.valueType = valueType  # type: int
        self.value = value  # type: Union[None, 'weidmueller.ucontrol.hub.VariableValueBoolean.VariableValueBooleanT', 'weidmueller.ucontrol.hub.VariableValueDuration.VariableValueDurationT', 'weidmueller.ucontrol.hub.VariableValueFloat64.VariableValueFloat64T', 'weidmueller.ucontrol.hub.VariableValueInt64.VariableValueInt64T', 'weidmueller.ucontrol.hub.VariableValueString.VariableValueStringT', 'weidmueller.ucontrol.hub.VariableValueTimestamp.VariableValueTimestampT']
        self.id = id  # type: int
        self.timestamp = timestamp  # type: Optional[weidmueller.ucontrol.hub.Timestamp.TimestampT]
        self.quality = quality  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variable = Variable()
        variable.Init(buf, pos)
        return cls.InitFromObj(variable)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variable):
        x = VariableT()
        x._UnPack(variable)
        return x

    # VariableT
    def _UnPack(self, variable):
        if variable is None:
            return
        self.valueType = variable.ValueType()
        self.value = weidmueller.ucontrol.hub.VariableValue.VariableValueCreator(self.valueType, variable.Value())
        self.id = variable.Id()
        if variable.Timestamp() is not None:
            self.timestamp = weidmueller.ucontrol.hub.Timestamp.TimestampT.InitFromObj(variable.Timestamp())
        self.quality = variable.Quality()

    # VariableT
    def Pack(self, builder):
        if self.value is not None:
            value = self.value.Pack(builder)
        VariableStart(builder)
        VariableAddValueType(builder, self.valueType)
        if self.value is not None:
            VariableAddValue(builder, value)
        VariableAddId(builder, self.id)
        if self.timestamp is not None:
            timestamp = self.timestamp.Pack(builder)
            VariableAddTimestamp(builder, timestamp)
        VariableAddQuality(builder, self.quality)
        variable = VariableEnd(builder)
        return variable
