# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# The definition of a variable.
class VariableDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The provider's unique key of the variable.
    # VariableDefinition
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The unique ID of the variable. It is only unique via one provider.
    # VariableDefinition
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The data type of the variable.
    # VariableDefinition
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # The access type of the variable.
    # VariableDefinition
    def AccessType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Marker to indicate whether the variable is experimental.
    #
    # Experimental means that the variable is not stable/reliable and it is hidden in the user interface.
    # VariableDefinition
    def Experimental(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VariableDefinitionStart(builder):
    builder.StartObject(5)

def Start(builder):
    VariableDefinitionStart(builder)

def VariableDefinitionAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    VariableDefinitionAddKey(builder, key)

def VariableDefinitionAddId(builder, id):
    builder.PrependUint32Slot(1, id, 0)

def AddId(builder, id):
    VariableDefinitionAddId(builder, id)

def VariableDefinitionAddDataType(builder, dataType):
    builder.PrependInt8Slot(2, dataType, 0)

def AddDataType(builder, dataType):
    VariableDefinitionAddDataType(builder, dataType)

def VariableDefinitionAddAccessType(builder, accessType):
    builder.PrependInt8Slot(3, accessType, 0)

def AddAccessType(builder, accessType):
    VariableDefinitionAddAccessType(builder, accessType)

def VariableDefinitionAddExperimental(builder, experimental):
    builder.PrependBoolSlot(4, experimental, 0)

def AddExperimental(builder, experimental):
    VariableDefinitionAddExperimental(builder, experimental)

def VariableDefinitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableDefinitionEnd(builder)


class VariableDefinitionT(object):

    # VariableDefinitionT
    def __init__(
        self,
        key = None,
        id = 0,
        dataType = 0,
        accessType = 0,
        experimental = False,
    ):
        self.key = key  # type: Optional[str]
        self.id = id  # type: int
        self.dataType = dataType  # type: int
        self.accessType = accessType  # type: int
        self.experimental = experimental  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableDefinition = VariableDefinition()
        variableDefinition.Init(buf, pos)
        return cls.InitFromObj(variableDefinition)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableDefinition):
        x = VariableDefinitionT()
        x._UnPack(variableDefinition)
        return x

    # VariableDefinitionT
    def _UnPack(self, variableDefinition):
        if variableDefinition is None:
            return
        self.key = variableDefinition.Key()
        self.id = variableDefinition.Id()
        self.dataType = variableDefinition.DataType()
        self.accessType = variableDefinition.AccessType()
        self.experimental = variableDefinition.Experimental()

    # VariableDefinitionT
    def Pack(self, builder):
        if self.key is not None:
            key = builder.CreateString(self.key)
        VariableDefinitionStart(builder)
        if self.key is not None:
            VariableDefinitionAddKey(builder, key)
        VariableDefinitionAddId(builder, self.id)
        VariableDefinitionAddDataType(builder, self.dataType)
        VariableDefinitionAddAccessType(builder, self.accessType)
        VariableDefinitionAddExperimental(builder, self.experimental)
        variableDefinition = VariableDefinitionEnd(builder)
        return variableDefinition
