# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# An event that describes a provider's list of variables that have just
# changed.
class VariablesChangedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariablesChangedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariablesChangedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariablesChangedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A list of variables that have just been changed.
    # Only contains changed variables!
    # VariablesChangedEvent
    def ChangedVariables(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.VariableList import VariableList
            obj = VariableList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VariablesChangedEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    VariablesChangedEventStart(builder)

def VariablesChangedEventAddChangedVariables(builder, changedVariables):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(changedVariables), 0)

def AddChangedVariables(builder, changedVariables):
    VariablesChangedEventAddChangedVariables(builder, changedVariables)

def VariablesChangedEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariablesChangedEventEnd(builder)

import weidmueller.ucontrol.hub.VariableList
try:
    from typing import Optional
except:
    pass

class VariablesChangedEventT(object):

    # VariablesChangedEventT
    def __init__(
        self,
        changedVariables = None,
    ):
        self.changedVariables = changedVariables  # type: Optional[weidmueller.ucontrol.hub.VariableList.VariableListT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variablesChangedEvent = VariablesChangedEvent()
        variablesChangedEvent.Init(buf, pos)
        return cls.InitFromObj(variablesChangedEvent)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variablesChangedEvent):
        x = VariablesChangedEventT()
        x._UnPack(variablesChangedEvent)
        return x

    # VariablesChangedEventT
    def _UnPack(self, variablesChangedEvent):
        if variablesChangedEvent is None:
            return
        if variablesChangedEvent.ChangedVariables() is not None:
            self.changedVariables = weidmueller.ucontrol.hub.VariableList.VariableListT.InitFromObj(variablesChangedEvent.ChangedVariables())

    # VariablesChangedEventT
    def Pack(self, builder):
        if self.changedVariables is not None:
            changedVariables = self.changedVariables.Pack(builder)
        VariablesChangedEventStart(builder)
        if self.changedVariables is not None:
            VariablesChangedEventAddChangedVariables(builder, changedVariables)
        variablesChangedEvent = VariablesChangedEventEnd(builder)
        return variablesChangedEvent
