# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A duration value of a variable.
class VariableValueDuration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableValueDuration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableValueDuration(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableValueDuration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariableValueDuration
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from weidmueller.ucontrol.hub.Duration import Duration
            obj = Duration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VariableValueDurationStart(builder):
    builder.StartObject(1)

def Start(builder):
    VariableValueDurationStart(builder)

def VariableValueDurationAddValue(builder, value):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    VariableValueDurationAddValue(builder, value)

def VariableValueDurationEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableValueDurationEnd(builder)

import weidmueller.ucontrol.hub.Duration
try:
    from typing import Optional
except:
    pass

class VariableValueDurationT(object):

    # VariableValueDurationT
    def __init__(
        self,
        value = None,
    ):
        self.value = value  # type: Optional[weidmueller.ucontrol.hub.Duration.DurationT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableValueDuration = VariableValueDuration()
        variableValueDuration.Init(buf, pos)
        return cls.InitFromObj(variableValueDuration)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableValueDuration):
        x = VariableValueDurationT()
        x._UnPack(variableValueDuration)
        return x

    # VariableValueDurationT
    def _UnPack(self, variableValueDuration):
        if variableValueDuration is None:
            return
        if variableValueDuration.Value() is not None:
            self.value = weidmueller.ucontrol.hub.Duration.DurationT.InitFromObj(variableValueDuration.Value())

    # VariableValueDurationT
    def Pack(self, builder):
        VariableValueDurationStart(builder)
        if self.value is not None:
            value = self.value.Pack(builder)
            VariableValueDurationAddValue(builder, value)
        variableValueDuration = VariableValueDurationEnd(builder)
        return variableValueDuration
