# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A boolean value of a variable.
class VariableValueBoolean(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableValueBoolean()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableValueBoolean(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableValueBoolean
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariableValueBoolean
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VariableValueBooleanStart(builder):
    builder.StartObject(1)

def Start(builder):
    VariableValueBooleanStart(builder)

def VariableValueBooleanAddValue(builder, value):
    builder.PrependBoolSlot(0, value, 0)

def AddValue(builder, value):
    VariableValueBooleanAddValue(builder, value)

def VariableValueBooleanEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableValueBooleanEnd(builder)


class VariableValueBooleanT(object):

    # VariableValueBooleanT
    def __init__(
        self,
        value = False,
    ):
        self.value = value  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableValueBoolean = VariableValueBoolean()
        variableValueBoolean.Init(buf, pos)
        return cls.InitFromObj(variableValueBoolean)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableValueBoolean):
        x = VariableValueBooleanT()
        x._UnPack(variableValueBoolean)
        return x

    # VariableValueBooleanT
    def _UnPack(self, variableValueBoolean):
        if variableValueBoolean is None:
            return
        self.value = variableValueBoolean.Value()

    # VariableValueBooleanT
    def Pack(self, builder):
        VariableValueBooleanStart(builder)
        VariableValueBooleanAddValue(builder, self.value)
        variableValueBoolean = VariableValueBooleanEnd(builder)
        return variableValueBoolean
