# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A string value of a variable.
class VariableValueString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableValueString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableValueString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableValueString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariableValueString
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def VariableValueStringStart(builder):
    builder.StartObject(1)

def Start(builder):
    VariableValueStringStart(builder)

def VariableValueStringAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    VariableValueStringAddValue(builder, value)

def VariableValueStringEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableValueStringEnd(builder)


class VariableValueStringT(object):

    # VariableValueStringT
    def __init__(
        self,
        value = None,
    ):
        self.value = value  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableValueString = VariableValueString()
        variableValueString.Init(buf, pos)
        return cls.InitFromObj(variableValueString)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableValueString):
        x = VariableValueStringT()
        x._UnPack(variableValueString)
        return x

    # VariableValueStringT
    def _UnPack(self, variableValueString):
        if variableValueString is None:
            return
        self.value = variableValueString.Value()

    # VariableValueStringT
    def Pack(self, builder):
        if self.value is not None:
            value = builder.CreateString(self.value)
        VariableValueStringStart(builder)
        if self.value is not None:
            VariableValueStringAddValue(builder, value)
        variableValueString = VariableValueStringEnd(builder)
        return variableValueString
