# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A precision floating-point value of a variable.
class VariableValueFloat64(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableValueFloat64()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableValueFloat64(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableValueFloat64
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariableValueFloat64
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def VariableValueFloat64Start(builder):
    builder.StartObject(1)

def Start(builder):
    VariableValueFloat64Start(builder)

def VariableValueFloat64AddValue(builder, value):
    builder.PrependFloat64Slot(0, value, 0.0)

def AddValue(builder, value):
    VariableValueFloat64AddValue(builder, value)

def VariableValueFloat64End(builder):
    return builder.EndObject()

def End(builder):
    return VariableValueFloat64End(builder)


class VariableValueFloat64T(object):

    # VariableValueFloat64T
    def __init__(
        self,
        value = 0.0,
    ):
        self.value = value  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableValueFloat64 = VariableValueFloat64()
        variableValueFloat64.Init(buf, pos)
        return cls.InitFromObj(variableValueFloat64)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableValueFloat64):
        x = VariableValueFloat64T()
        x._UnPack(variableValueFloat64)
        return x

    # VariableValueFloat64T
    def _UnPack(self, variableValueFloat64):
        if variableValueFloat64 is None:
            return
        self.value = variableValueFloat64.Value()

    # VariableValueFloat64T
    def Pack(self, builder):
        VariableValueFloat64Start(builder)
        VariableValueFloat64AddValue(builder, self.value)
        variableValueFloat64 = VariableValueFloat64End(builder)
        return variableValueFloat64
