# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A 64-bit, signed integer value of a variable.
class VariableValueInt64(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariableValueInt64()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariableValueInt64(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariableValueInt64
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariableValueInt64
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def VariableValueInt64Start(builder):
    builder.StartObject(1)

def Start(builder):
    VariableValueInt64Start(builder)

def VariableValueInt64AddValue(builder, value):
    builder.PrependInt64Slot(0, value, 0)

def AddValue(builder, value):
    VariableValueInt64AddValue(builder, value)

def VariableValueInt64End(builder):
    return builder.EndObject()

def End(builder):
    return VariableValueInt64End(builder)


class VariableValueInt64T(object):

    # VariableValueInt64T
    def __init__(
        self,
        value = 0,
    ):
        self.value = value  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        variableValueInt64 = VariableValueInt64()
        variableValueInt64.Init(buf, pos)
        return cls.InitFromObj(variableValueInt64)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, variableValueInt64):
        x = VariableValueInt64T()
        x._UnPack(variableValueInt64)
        return x

    # VariableValueInt64T
    def _UnPack(self, variableValueInt64):
        if variableValueInt64 is None:
            return
        self.value = variableValueInt64.Value()

    # VariableValueInt64T
    def Pack(self, builder):
        VariableValueInt64Start(builder)
        VariableValueInt64AddValue(builder, self.value)
        variableValueInt64 = VariableValueInt64End(builder)
        return variableValueInt64
