# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

# The access type of a variable.
class VariableAccessType(object):
    UNSPECIFIED = 0
    # Consumers can only read the variable.
    READ_ONLY = 1
    # Consumers can read and write the variable.
    READ_WRITE = 2
