# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A command writing a list of provider variables.
class WriteVariablesCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WriteVariablesCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWriteVariablesCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WriteVariablesCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # A list of variables that have to be written.
    # WriteVariablesCommand
    def Variables(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from weidmueller.ucontrol.hub.VariableList import VariableList
            obj = VariableList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WriteVariablesCommandStart(builder):
    builder.StartObject(1)

def Start(builder):
    WriteVariablesCommandStart(builder)

def WriteVariablesCommandAddVariables(builder, variables):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(variables), 0)

def AddVariables(builder, variables):
    WriteVariablesCommandAddVariables(builder, variables)

def WriteVariablesCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return WriteVariablesCommandEnd(builder)

import weidmueller.ucontrol.hub.VariableList
try:
    from typing import Optional
except:
    pass

class WriteVariablesCommandT(object):

    # WriteVariablesCommandT
    def __init__(
        self,
        variables = None,
    ):
        self.variables = variables  # type: Optional[weidmueller.ucontrol.hub.VariableList.VariableListT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        writeVariablesCommand = WriteVariablesCommand()
        writeVariablesCommand.Init(buf, pos)
        return cls.InitFromObj(writeVariablesCommand)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, writeVariablesCommand):
        x = WriteVariablesCommandT()
        x._UnPack(writeVariablesCommand)
        return x

    # WriteVariablesCommandT
    def _UnPack(self, writeVariablesCommand):
        if writeVariablesCommand is None:
            return
        if writeVariablesCommand.Variables() is not None:
            self.variables = weidmueller.ucontrol.hub.VariableList.VariableListT.InitFromObj(writeVariablesCommand.Variables())

    # WriteVariablesCommandT
    def Pack(self, builder):
        if self.variables is not None:
            variables = self.variables.Pack(builder)
        WriteVariablesCommandStart(builder)
        if self.variables is not None:
            WriteVariablesCommandAddVariables(builder, variables)
        writeVariablesCommand = WriteVariablesCommandEnd(builder)
        return writeVariablesCommand
